# Generated by Django 5.0 on 2023-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_allcars_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcars',
            name='car_max_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allcars',
            name='car_top_speed',
            field=models.IntegerField(default=0),
        ),
    ]
