# Generated by Django 5.0 on 2023-12-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_allcars_car_max_power_allcars_car_top_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcars',
            name='car_max_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allcars',
            name='car_top_speed',
            field=models.IntegerField(),
        ),
    ]
