# Generated by Django 5.0 on 2023-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_allcars_car_max_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcars',
            name='car_max_power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='allcars',
            name='car_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='allcars',
            name='car_top_speed',
            field=models.FloatField(),
        ),
    ]
